org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Users/Lunix/.jdks/openjdk-26
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=0.1.10.2
maven_group=net.lunix
archives_base_name=lethemc
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.153.0+26.2
